# Generated by Django 4.0.4 on 2022-05-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_num', models.CharField(max_length=255, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время посещения')),
                ('lat', models.FloatField(verbose_name='Широта/Latitude')),
                ('long', models.FloatField(verbose_name='Долгота/longitude')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobil_api.pos', verbose_name='Торговая точка')),
            ],
        ),
        migrations.AddField(
            model_name='pos',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobil_api.worker', verbose_name='Работник'),
        ),
    ]
