# Generated by Django 4.0.4 on 2022-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'ordering': ('pos_name',), 'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговые точки'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('date',), 'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('name',), 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
