# Generated by Django 4.0.4 on 2022-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobil_api', '0002_alter_pos_options_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время посещения'),
        ),
    ]
